on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    types: [opened, reopened, synchronize]
  workflow_call:
  workflow_dispatch:

name: ci-build

env:
  DOTNET_VERSION: 9.0.x
  REGISTRY: ghcr.io

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Publish ShockOSC
        run: dotnet publish ShockOsc/ShockOsc.csproj -c Release -o ./publish/

      - name: Upload ShockOSC artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ShockOsc
          path: publish/*
          retention-days: 1
          if-no-files-found: error